### PR TITLE
Add ConfigureAwait inside ConnectAsync

### PR DESCRIPTION
**Pull request by rhofstra-sefi**
CosmosContainerInitializeAsync without ConfigureAwait was causing the await to never return

### CODE REVIEW

**Comment by ealsur** [comment]
@rhofstra-sefi Are you initializing the call blocking instead of awaiting it? ConfigureAwait helps on the scenario where you are running within a synchronizationcontext only.

**Comment by ealsur** [comment]
Also, the code inside `ConnectAsync` has `ConfigureAwait(false)` already on all the async calls, what is the added benefit of adding it there? Does it really solve your issue? If your call is never returning that might be sign of something else

**Comment by rhofstra-sefi** [comment]
> 
> 
> @rhofstra-sefi Are you initializing the call blocking instead of awaiting it? ConfigureAwait helps on the scenario where you are running within a synchronizationcontext only.

I started out using the synchronous Get(string key) in an application I'm working on.  When I had issues, I forked and started debugging, and noticed that `await this.CosmosContainerInitializeAsync()` was failing to return, even though the actual method would run without any errors and make it to the return statement.  Adding the ConfigureAwait there (and in the calling ConnectAsyncs) did in fact fix the problem.  The connection lock inside ConnectAsync has a ConfigureAwait, while the actual async call inside the lock does not, which I think was causing a deadlock.

**Comment by ealsur** [comment]
@rhofstra-sefi Released on 1.0.0-preview3

**Pull request merged**
